= Security

Notes about security.

== Encryption

The connection between the client and the server is not encrypted.

== Passwords

Account "passwords" are hashed server-side with SHA-512 and a random salt which has the same size as the hash output. Before being sent to the server, since the connection is not encrypted, client passwords are also hashed with SHA-512 with a constant salt and the identifier.

As an improvement, the client password would use a function like Argon2 instead. Not server-side to not increase the potential of DDOS attacks while still giving protection because an attacker would have a hash-to-hash relationship instead of a password-to-hash.

Unfortunately, having a cryptographic dependency client-side would add complexity and require more work to support all platforms, which seems out of scope of the project. The current security is probably better than nothing.

It is interesting to note that password authentication is not ideal anyway and people should stop trusting services with their secrets.
